version: '3.8'
networks:
  mi_red:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

services:
   mysql:
    image: mysql:latest
    networks:
      mi_red:
        ipv4_address: 172.18.0.3
    environment:
      MYSQL_ROOT_PASSWORD: sovier
      MYSQL_DATABASE: bdpaises
      MYSQL_USER: secros
      MYSQL_PASSWORD: sovier
    ports:
      - "3306:3306"
    restart: always
    
   net-core-concepts:
    image: net-core-concepts:latest
    networks:
      mi_red:
        ipv4_address: 172.18.0.2
    build:
      context: .
      dockerfile: NetCoreConcepts/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=/.nuget/fallbackpackages
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_VERSION=6.0.26
      - ASPNET_VERSION=6.0.26
    volumes:
      - C:\Users\Gamer\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Gamer\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\Gamer\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\Gamer\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\TokenService.Proxy\linux-x64\net6.0:/TokenService.Proxy:ro
    restart: no

    
    
